name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  Test:
    name: Running Unit Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test persona_unittest
      run: ./persona_unittest
